name: Github Labels Workflow

on: push

#  schedule:
#    - cron: 0 0 * * 0

jobs:
  labels:
    name: Create Github labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Download labels script
        run: yarn global add github-label-sync

      - name: Run script to create Github labels
        run: github-label-sync --labels .github/labels.yml patryk-szydlowski/capybara
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
